Replace MPRIS implementation
ddddxxx/MusicPlayer pull request #12
Opened 2024-10-08 13:00 UTC by suransea

I created the `dbus-swift` and `mpris-swift` libraries, providing a new `MPRIS` implementation. The new implementation eliminates external dependencies and adds support for `macOS`.

Changes: 
- Removed the old MPRIS implementation.
- Integrated a new MPRIS implementation for better compatibility.
- Updated relevant code and dependencies to support the new implementation.

2024-10-08 13:06 UTC, suransea commented
The CI build is currently failing because Swift 6 is not available.

2024-10-10 13:59 UTC, ddddxxx requested changes
It's been a while :). The new MPRIS implementation looks brilliant. Here's my suggestion. Thank you!

2024-10-10 13:59 UTC, ddddxxx commented on .clang-format
do not commit unrelated files (also gitignore).

2024-10-10 13:59 UTC, ddddxxx commented on Sources/MusicPlayer/Players/MPRIS.swift
> +            disposables.append(try player.player.seeked { _ in updatePlayerState() })
[weak self]

2024-10-10 13:59 UTC, ddddxxx commented on Sources/MusicPlayer/Players/MPRIS.swift
> +            disposables.forEach { try? $0() }
The name is misleading, we can't just dispose of them, right?

Can you wrap them in DBus library, like this?

```swift
class DBusHandlerRegistation {
    typealias UnregisterFuction = () throws(DBus.Error) -> Void
    let unregister: UnregisterFuction
    deinit {
        try? unregister()
    }
}
```

2024-10-10 13:59 UTC, ddddxxx commented on Sources/MusicPlayer/Players/MPRIS.swift
> +    public var name: MusicPlayerName? { nil }
use bus name? or just `.mpris` if not feasible.

2024-10-10 13:59 UTC, ddddxxx commented on Sources/MusicPlayer/Players/MPRIS.swift
> +        name: String, instance: String? = nil, queue: DispatchQueue? = nil
I think it's better to make it as simple as possible, treat queue, connection, and timeout as implementation details and don't expose them. We can always expose them later if someone needs it.

2024-10-10 13:59 UTC, ddddxxx commented on Sources/MusicPlayer/Players/MPRISNowPlaying.swift
> +    public final class MPRISNowPlaying: Agent {
Here we have player selection logic twice, in different repo. How about deriving from `NowPlaying`, only update player list and let `NowPlaying` do the selection?

2024-10-12 16:34 UTC, closed without merging